### YamlMime:ManagedReference
items:
- uid: WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs
  commentId: T:WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs
  id: GetAllSubjectsMeansCompletedEventArgs
  parent: WebApplication.TimeMeanWebService
  children:
  - WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs.Result
  langs:
  - csharp
  - vb
  name: GetAllSubjectsMeansCompletedEventArgs
  nameWithType: GetAllSubjectsMeansCompletedEventArgs
  fullName: WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs
  type: Class
  source:
    remote:
      path: WebApplication/Web References/TimeMeanWebService/Reference.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: GetAllSubjectsMeansCompletedEventArgs
    path: ../WebApplication/Web References/TimeMeanWebService/Reference.cs
    startLine: 160
  assemblies:
  - WebApplication
  namespace: WebApplication.TimeMeanWebService
  remarks: ''
  example: []
  syntax:
    content: 'public class GetAllSubjectsMeansCompletedEventArgs : AsyncCompletedEventArgs'
    content.vb: >-
      Public Class GetAllSubjectsMeansCompletedEventArgs
          Inherits AsyncCompletedEventArgs
  inheritance:
  - System.Object
  - System.EventArgs
  - System.ComponentModel.AsyncCompletedEventArgs
  inheritedMembers:
  - System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary
  - System.ComponentModel.AsyncCompletedEventArgs.Cancelled
  - System.ComponentModel.AsyncCompletedEventArgs.Error
  - System.ComponentModel.AsyncCompletedEventArgs.UserState
  - System.EventArgs.Empty
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs.Result
  commentId: P:WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs.Result
  id: Result
  parent: WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs
  langs:
  - csharp
  - vb
  name: Result
  nameWithType: GetAllSubjectsMeansCompletedEventArgs.Result
  fullName: WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs.Result
  type: Property
  source:
    remote:
      path: WebApplication/Web References/TimeMeanWebService/Reference.cs
      branch: FerMod
      repo: git@github.com:FerMod/HADSProject.git
    id: Result
    path: ../WebApplication/Web References/TimeMeanWebService/Reference.cs
    startLine: 173
  assemblies:
  - WebApplication
  namespace: WebApplication.TimeMeanWebService
  remarks: ''
  example: []
  syntax:
    content: public DataTable Result { get; }
    parameters: []
    return:
      type: System.Data.DataTable
    content.vb: Public ReadOnly Property Result As DataTable
  overload: WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs.Result*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: WebApplication.TimeMeanWebService
  commentId: N:WebApplication.TimeMeanWebService
  name: WebApplication.TimeMeanWebService
  nameWithType: WebApplication.TimeMeanWebService
  fullName: WebApplication.TimeMeanWebService
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.EventArgs
  commentId: T:System.EventArgs
  parent: System
  isExternal: true
  name: EventArgs
  nameWithType: EventArgs
  fullName: System.EventArgs
- uid: System.ComponentModel.AsyncCompletedEventArgs
  commentId: T:System.ComponentModel.AsyncCompletedEventArgs
  parent: System.ComponentModel
  isExternal: true
  name: AsyncCompletedEventArgs
  nameWithType: AsyncCompletedEventArgs
  fullName: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary
  commentId: M:System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary
  parent: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: true
  name: RaiseExceptionIfNecessary()
  nameWithType: AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
  fullName: System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
  spec.csharp:
  - uid: System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary
    name: RaiseExceptionIfNecessary
    nameWithType: AsyncCompletedEventArgs.RaiseExceptionIfNecessary
    fullName: System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary
    name: RaiseExceptionIfNecessary
    nameWithType: AsyncCompletedEventArgs.RaiseExceptionIfNecessary
    fullName: System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ComponentModel.AsyncCompletedEventArgs.Cancelled
  commentId: P:System.ComponentModel.AsyncCompletedEventArgs.Cancelled
  parent: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: true
  name: Cancelled
  nameWithType: AsyncCompletedEventArgs.Cancelled
  fullName: System.ComponentModel.AsyncCompletedEventArgs.Cancelled
- uid: System.ComponentModel.AsyncCompletedEventArgs.Error
  commentId: P:System.ComponentModel.AsyncCompletedEventArgs.Error
  parent: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: true
  name: Error
  nameWithType: AsyncCompletedEventArgs.Error
  fullName: System.ComponentModel.AsyncCompletedEventArgs.Error
- uid: System.ComponentModel.AsyncCompletedEventArgs.UserState
  commentId: P:System.ComponentModel.AsyncCompletedEventArgs.UserState
  parent: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: true
  name: UserState
  nameWithType: AsyncCompletedEventArgs.UserState
  fullName: System.ComponentModel.AsyncCompletedEventArgs.UserState
- uid: System.EventArgs.Empty
  commentId: F:System.EventArgs.Empty
  parent: System.EventArgs
  isExternal: true
  name: Empty
  nameWithType: EventArgs.Empty
  fullName: System.EventArgs.Empty
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.ComponentModel
  commentId: N:System.ComponentModel
  isExternal: true
  name: System.ComponentModel
  nameWithType: System.ComponentModel
  fullName: System.ComponentModel
- uid: WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs.Result*
  commentId: Overload:WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs.Result
  name: Result
  nameWithType: GetAllSubjectsMeansCompletedEventArgs.Result
  fullName: WebApplication.TimeMeanWebService.GetAllSubjectsMeansCompletedEventArgs.Result
- uid: System.Data.DataTable
  commentId: T:System.Data.DataTable
  parent: System.Data
  isExternal: true
  name: DataTable
  nameWithType: DataTable
  fullName: System.Data.DataTable
- uid: System.Data
  commentId: N:System.Data
  isExternal: true
  name: System.Data
  nameWithType: System.Data
  fullName: System.Data
