### YamlMime:ManagedReference
items:
- uid: WebApplication.AppConfig.SmtpServer
  commentId: T:WebApplication.AppConfig.SmtpServer
  id: AppConfig.SmtpServer
  parent: WebApplication
  children:
  - WebApplication.AppConfig.SmtpServer.Account
  - WebApplication.AppConfig.SmtpServer.DeliveryMethod
  - WebApplication.AppConfig.SmtpServer.EnableSsl
  - WebApplication.AppConfig.SmtpServer.Host
  - WebApplication.AppConfig.SmtpServer.Password
  - WebApplication.AppConfig.SmtpServer.Port
  - WebApplication.AppConfig.SmtpServer.UseDefaultCredentials
  langs:
  - csharp
  - vb
  name: AppConfig.SmtpServer
  nameWithType: AppConfig.SmtpServer
  fullName: WebApplication.AppConfig.SmtpServer
  type: Class
  source:
    remote:
      path: WebApplication/AppConfig.cs
      branch: master
      repo: git@github.com:FerMod/HADSProject.git
    id: SmtpServer
    path: ../WebApplication/AppConfig.cs
    startLine: 13
  assemblies:
  - WebApplication
  namespace: WebApplication
  syntax:
    content: public static class SmtpServer
    content.vb: Public Module SmtpServer
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: WebApplication.AppConfig.SmtpServer.Account
  commentId: P:WebApplication.AppConfig.SmtpServer.Account
  id: Account
  parent: WebApplication.AppConfig.SmtpServer
  langs:
  - csharp
  - vb
  name: Account
  nameWithType: AppConfig.SmtpServer.Account
  fullName: WebApplication.AppConfig.SmtpServer.Account
  type: Property
  source:
    remote:
      path: WebApplication/AppConfig.cs
      branch: master
      repo: git@github.com:FerMod/HADSProject.git
    id: Account
    path: ../WebApplication/AppConfig.cs
    startLine: 18
  assemblies:
  - WebApplication
  namespace: WebApplication
  summary: "\n\n"
  example: []
  syntax:
    content: public static string Account { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property Account As String
  overload: WebApplication.AppConfig.SmtpServer.Account*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: WebApplication.AppConfig.SmtpServer.Password
  commentId: P:WebApplication.AppConfig.SmtpServer.Password
  id: Password
  parent: WebApplication.AppConfig.SmtpServer
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: AppConfig.SmtpServer.Password
  fullName: WebApplication.AppConfig.SmtpServer.Password
  type: Property
  source:
    remote:
      path: WebApplication/AppConfig.cs
      branch: master
      repo: git@github.com:FerMod/HADSProject.git
    id: Password
    path: ../WebApplication/AppConfig.cs
    startLine: 23
  assemblies:
  - WebApplication
  namespace: WebApplication
  summary: "\n\n"
  example: []
  syntax:
    content: public static string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property Password As String
  overload: WebApplication.AppConfig.SmtpServer.Password*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: WebApplication.AppConfig.SmtpServer.Host
  commentId: P:WebApplication.AppConfig.SmtpServer.Host
  id: Host
  parent: WebApplication.AppConfig.SmtpServer
  langs:
  - csharp
  - vb
  name: Host
  nameWithType: AppConfig.SmtpServer.Host
  fullName: WebApplication.AppConfig.SmtpServer.Host
  type: Property
  source:
    remote:
      path: WebApplication/AppConfig.cs
      branch: master
      repo: git@github.com:FerMod/HADSProject.git
    id: Host
    path: ../WebApplication/AppConfig.cs
    startLine: 28
  assemblies:
  - WebApplication
  namespace: WebApplication
  summary: "\n\n"
  example: []
  syntax:
    content: public static string Host { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property Host As String
  overload: WebApplication.AppConfig.SmtpServer.Host*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: WebApplication.AppConfig.SmtpServer.Port
  commentId: P:WebApplication.AppConfig.SmtpServer.Port
  id: Port
  parent: WebApplication.AppConfig.SmtpServer
  langs:
  - csharp
  - vb
  name: Port
  nameWithType: AppConfig.SmtpServer.Port
  fullName: WebApplication.AppConfig.SmtpServer.Port
  type: Property
  source:
    remote:
      path: WebApplication/AppConfig.cs
      branch: master
      repo: git@github.com:FerMod/HADSProject.git
    id: Port
    path: ../WebApplication/AppConfig.cs
    startLine: 33
  assemblies:
  - WebApplication
  namespace: WebApplication
  summary: "\n\n"
  example: []
  syntax:
    content: public static int Port { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property Port As Integer
  overload: WebApplication.AppConfig.SmtpServer.Port*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: WebApplication.AppConfig.SmtpServer.DeliveryMethod
  commentId: P:WebApplication.AppConfig.SmtpServer.DeliveryMethod
  id: DeliveryMethod
  parent: WebApplication.AppConfig.SmtpServer
  langs:
  - csharp
  - vb
  name: DeliveryMethod
  nameWithType: AppConfig.SmtpServer.DeliveryMethod
  fullName: WebApplication.AppConfig.SmtpServer.DeliveryMethod
  type: Property
  source:
    remote:
      path: WebApplication/AppConfig.cs
      branch: master
      repo: git@github.com:FerMod/HADSProject.git
    id: DeliveryMethod
    path: ../WebApplication/AppConfig.cs
    startLine: 38
  assemblies:
  - WebApplication
  namespace: WebApplication
  summary: "\n\n"
  example: []
  syntax:
    content: public static SmtpDeliveryMethod DeliveryMethod { get; set; }
    parameters: []
    return:
      type: System.Net.Mail.SmtpDeliveryMethod
    content.vb: Public Shared Property DeliveryMethod As SmtpDeliveryMethod
  overload: WebApplication.AppConfig.SmtpServer.DeliveryMethod*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: WebApplication.AppConfig.SmtpServer.UseDefaultCredentials
  commentId: P:WebApplication.AppConfig.SmtpServer.UseDefaultCredentials
  id: UseDefaultCredentials
  parent: WebApplication.AppConfig.SmtpServer
  langs:
  - csharp
  - vb
  name: UseDefaultCredentials
  nameWithType: AppConfig.SmtpServer.UseDefaultCredentials
  fullName: WebApplication.AppConfig.SmtpServer.UseDefaultCredentials
  type: Property
  source:
    remote:
      path: WebApplication/AppConfig.cs
      branch: master
      repo: git@github.com:FerMod/HADSProject.git
    id: UseDefaultCredentials
    path: ../WebApplication/AppConfig.cs
    startLine: 43
  assemblies:
  - WebApplication
  namespace: WebApplication
  summary: "\n\n"
  example: []
  syntax:
    content: public static bool UseDefaultCredentials { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property UseDefaultCredentials As Boolean
  overload: WebApplication.AppConfig.SmtpServer.UseDefaultCredentials*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
- uid: WebApplication.AppConfig.SmtpServer.EnableSsl
  commentId: P:WebApplication.AppConfig.SmtpServer.EnableSsl
  id: EnableSsl
  parent: WebApplication.AppConfig.SmtpServer
  langs:
  - csharp
  - vb
  name: EnableSsl
  nameWithType: AppConfig.SmtpServer.EnableSsl
  fullName: WebApplication.AppConfig.SmtpServer.EnableSsl
  type: Property
  source:
    remote:
      path: WebApplication/AppConfig.cs
      branch: master
      repo: git@github.com:FerMod/HADSProject.git
    id: EnableSsl
    path: ../WebApplication/AppConfig.cs
    startLine: 48
  assemblies:
  - WebApplication
  namespace: WebApplication
  summary: "\n\n"
  example: []
  syntax:
    content: public static bool EnableSsl { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property EnableSsl As Boolean
  overload: WebApplication.AppConfig.SmtpServer.EnableSsl*
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
references:
- uid: WebApplication
  commentId: N:WebApplication
  name: WebApplication
  nameWithType: WebApplication
  fullName: WebApplication
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: WebApplication.AppConfig.SmtpServer.Account*
  commentId: Overload:WebApplication.AppConfig.SmtpServer.Account
  name: Account
  nameWithType: AppConfig.SmtpServer.Account
  fullName: WebApplication.AppConfig.SmtpServer.Account
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: WebApplication.AppConfig.SmtpServer.Password*
  commentId: Overload:WebApplication.AppConfig.SmtpServer.Password
  name: Password
  nameWithType: AppConfig.SmtpServer.Password
  fullName: WebApplication.AppConfig.SmtpServer.Password
- uid: WebApplication.AppConfig.SmtpServer.Host*
  commentId: Overload:WebApplication.AppConfig.SmtpServer.Host
  name: Host
  nameWithType: AppConfig.SmtpServer.Host
  fullName: WebApplication.AppConfig.SmtpServer.Host
- uid: WebApplication.AppConfig.SmtpServer.Port*
  commentId: Overload:WebApplication.AppConfig.SmtpServer.Port
  name: Port
  nameWithType: AppConfig.SmtpServer.Port
  fullName: WebApplication.AppConfig.SmtpServer.Port
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: WebApplication.AppConfig.SmtpServer.DeliveryMethod*
  commentId: Overload:WebApplication.AppConfig.SmtpServer.DeliveryMethod
  name: DeliveryMethod
  nameWithType: AppConfig.SmtpServer.DeliveryMethod
  fullName: WebApplication.AppConfig.SmtpServer.DeliveryMethod
- uid: System.Net.Mail.SmtpDeliveryMethod
  commentId: T:System.Net.Mail.SmtpDeliveryMethod
  parent: System.Net.Mail
  isExternal: true
  name: SmtpDeliveryMethod
  nameWithType: SmtpDeliveryMethod
  fullName: System.Net.Mail.SmtpDeliveryMethod
- uid: System.Net.Mail
  commentId: N:System.Net.Mail
  isExternal: true
  name: System.Net.Mail
  nameWithType: System.Net.Mail
  fullName: System.Net.Mail
- uid: WebApplication.AppConfig.SmtpServer.UseDefaultCredentials*
  commentId: Overload:WebApplication.AppConfig.SmtpServer.UseDefaultCredentials
  name: UseDefaultCredentials
  nameWithType: AppConfig.SmtpServer.UseDefaultCredentials
  fullName: WebApplication.AppConfig.SmtpServer.UseDefaultCredentials
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: WebApplication.AppConfig.SmtpServer.EnableSsl*
  commentId: Overload:WebApplication.AppConfig.SmtpServer.EnableSsl
  name: EnableSsl
  nameWithType: AppConfig.SmtpServer.EnableSsl
  fullName: WebApplication.AppConfig.SmtpServer.EnableSsl
