### YamlMime:ManagedReference
items:
- uid: WebApplication.Framework.AlertLevel
  commentId: T:WebApplication.Framework.AlertLevel
  id: AlertLevel
  parent: WebApplication.Framework
  children:
  - WebApplication.Framework.AlertLevel.Danger
  - WebApplication.Framework.AlertLevel.Dark
  - WebApplication.Framework.AlertLevel.Info
  - WebApplication.Framework.AlertLevel.Light
  - WebApplication.Framework.AlertLevel.None
  - WebApplication.Framework.AlertLevel.op_Explicit(System.String)~WebApplication.Framework.AlertLevel
  - WebApplication.Framework.AlertLevel.Primary
  - WebApplication.Framework.AlertLevel.Secondary
  - WebApplication.Framework.AlertLevel.Success
  - WebApplication.Framework.AlertLevel.ToString
  - WebApplication.Framework.AlertLevel.Warning
  langs:
  - csharp
  - vb
  name: AlertLevel
  nameWithType: AlertLevel
  fullName: WebApplication.Framework.AlertLevel
  type: Class
  source:
    id: AlertLevel
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 11
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  summary: "\nClass to act like an enum, that holds different values.\nThis class specifies the alert level.\n"
  example: []
  syntax:
    content: public sealed class AlertLevel
    content.vb: Public NotInheritable Class AlertLevel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: WebApplication.Framework.AlertLevel.None
  commentId: F:WebApplication.Framework.AlertLevel.None
  id: None
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: None
  nameWithType: AlertLevel.None
  fullName: WebApplication.Framework.AlertLevel.None
  type: Field
  source:
    id: None
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 18
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel None
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly None As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.Primary
  commentId: F:WebApplication.Framework.AlertLevel.Primary
  id: Primary
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Primary
  nameWithType: AlertLevel.Primary
  fullName: WebApplication.Framework.AlertLevel.Primary
  type: Field
  source:
    id: Primary
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 19
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel Primary
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly Primary As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.Secondary
  commentId: F:WebApplication.Framework.AlertLevel.Secondary
  id: Secondary
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Secondary
  nameWithType: AlertLevel.Secondary
  fullName: WebApplication.Framework.AlertLevel.Secondary
  type: Field
  source:
    id: Secondary
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 20
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel Secondary
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly Secondary As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.Success
  commentId: F:WebApplication.Framework.AlertLevel.Success
  id: Success
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Success
  nameWithType: AlertLevel.Success
  fullName: WebApplication.Framework.AlertLevel.Success
  type: Field
  source:
    id: Success
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 21
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel Success
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly Success As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.Danger
  commentId: F:WebApplication.Framework.AlertLevel.Danger
  id: Danger
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Danger
  nameWithType: AlertLevel.Danger
  fullName: WebApplication.Framework.AlertLevel.Danger
  type: Field
  source:
    id: Danger
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 22
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel Danger
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly Danger As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.Warning
  commentId: F:WebApplication.Framework.AlertLevel.Warning
  id: Warning
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Warning
  nameWithType: AlertLevel.Warning
  fullName: WebApplication.Framework.AlertLevel.Warning
  type: Field
  source:
    id: Warning
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 23
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel Warning
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly Warning As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.Info
  commentId: F:WebApplication.Framework.AlertLevel.Info
  id: Info
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Info
  nameWithType: AlertLevel.Info
  fullName: WebApplication.Framework.AlertLevel.Info
  type: Field
  source:
    id: Info
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 24
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel Info
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly Info As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.Light
  commentId: F:WebApplication.Framework.AlertLevel.Light
  id: Light
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Light
  nameWithType: AlertLevel.Light
  fullName: WebApplication.Framework.AlertLevel.Light
  type: Field
  source:
    id: Light
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 25
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel Light
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly Light As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.Dark
  commentId: F:WebApplication.Framework.AlertLevel.Dark
  id: Dark
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Dark
  nameWithType: AlertLevel.Dark
  fullName: WebApplication.Framework.AlertLevel.Dark
  type: Field
  source:
    id: Dark
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 26
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static readonly AlertLevel Dark
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared ReadOnly Dark As AlertLevel
  modifiers.csharp:
  - public
  - static
  - readonly
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: WebApplication.Framework.AlertLevel.ToString
  commentId: M:WebApplication.Framework.AlertLevel.ToString
  id: ToString
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: AlertLevel.ToString()
  fullName: WebApplication.Framework.AlertLevel.ToString()
  type: Method
  source:
    id: ToString
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 34
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public override string ToString()
    return:
      type: System.String
    content.vb: Public Overrides Function ToString As String
  overridden: System.Object.ToString
  overload: WebApplication.Framework.AlertLevel.ToString*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: WebApplication.Framework.AlertLevel.op_Explicit(System.String)~WebApplication.Framework.AlertLevel
  commentId: M:WebApplication.Framework.AlertLevel.op_Explicit(System.String)~WebApplication.Framework.AlertLevel
  id: op_Explicit(System.String)~WebApplication.Framework.AlertLevel
  parent: WebApplication.Framework.AlertLevel
  langs:
  - csharp
  - vb
  name: Explicit(String to AlertLevel)
  nameWithType: AlertLevel.Explicit(String to AlertLevel)
  fullName: WebApplication.Framework.AlertLevel.Explicit(System.String to WebApplication.Framework.AlertLevel)
  type: Operator
  source:
    id: op_Explicit
    path: D:\Users\Ferran\source\repos\HADSProject\WebApplication\Framework\AlertLevel.cs
    startLine: 38
  assemblies:
  - WebApplication
  namespace: WebApplication.Framework
  syntax:
    content: public static explicit operator AlertLevel(string str)
    parameters:
    - id: str
      type: System.String
    return:
      type: WebApplication.Framework.AlertLevel
    content.vb: Public Shared Narrowing Operator CType(str As String) As AlertLevel
  overload: WebApplication.Framework.AlertLevel.op_Explicit*
  nameWithType.vb: AlertLevel.Narrowing(String to AlertLevel)
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: WebApplication.Framework.AlertLevel.Narrowing(System.String to WebApplication.Framework.AlertLevel)
  name.vb: Narrowing(String to AlertLevel)
references:
- uid: WebApplication.Framework
  commentId: N:WebApplication.Framework
  name: WebApplication.Framework
  nameWithType: WebApplication.Framework
  fullName: WebApplication.Framework
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: WebApplication.Framework.AlertLevel
  commentId: T:WebApplication.Framework.AlertLevel
  parent: WebApplication.Framework
  name: AlertLevel
  nameWithType: AlertLevel
  fullName: WebApplication.Framework.AlertLevel
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: WebApplication.Framework.AlertLevel.ToString*
  commentId: Overload:WebApplication.Framework.AlertLevel.ToString
  name: ToString
  nameWithType: AlertLevel.ToString
  fullName: WebApplication.Framework.AlertLevel.ToString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: WebApplication.Framework.AlertLevel.op_Explicit*
  commentId: Overload:WebApplication.Framework.AlertLevel.op_Explicit
  name: Explicit
  nameWithType: AlertLevel.Explicit
  fullName: WebApplication.Framework.AlertLevel.Explicit
  nameWithType.vb: AlertLevel.Narrowing
  fullName.vb: WebApplication.Framework.AlertLevel.Narrowing
  name.vb: Narrowing
